module.exports = {
  mode: "jit",
  content: ["./src/**/*.{html,js}"],
  darkMode: false, // or 'media' or 'class'
  purge: ["./src/**/*.js", "./public/index.html"],
  theme: {
    extend: {},
    fontFamily: {
      sans: ["Roboto", "sans-serif"],
      serif: ["Roboto Slab", "serif"],
      body: ["Roboto", "sans-serif"],
      Nunito: ["Nunito", "sans-serif"],
      Open: ["Open Sans", "sans-serif"],
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      mainPurple: "#062747",
      lightPurple: "#020d18",
      mainBlue: "#A1B4F5",
      mainRed: "#DD003F",
      mainRedBlur: "rgb(221, 0, 63,0.5)",
      white: "#fff",
      whiteBlur: "rgba(255, 255, 255,0.7)",
      whiteC4: "rgba(196, 196, 196, 0.8);",
      mainPurpleBlur: "rgba(4, 0, 40,0.8)",
      lightPurpleBlur: "rgb(32, 34, 88,0.7)",
      mainRedBlur: "rgba(221, 0, 63,0.5)",
      blackBlur: "rgba(0,0,0,0.55)",
      blackBlurHevy: "rgba(0,0,0,0.85)",
      blackOpacity: "rgba(0,0,0,0.18)",
      black: "rgba(0,0,0)",
      yellow: "#FFB800",
      gray: "#828CBD",
      opa: "rgba(0,0,0,0.5)",
      orange: "#F24E1E",
      green: "#008000",
      pink: "#870164",
    },
  },
  plugins: [],
};
